version: '3'

services:
  open-ip:
    build: ./
    environment:
      - DISPLAY=${DISPLAY}
    env_file:
      - env-variables.env
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    privileged: true
    user: "1000:1000"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    user: "1000:1000"